theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
gutters = ["diagnostics", "line-numbers", "spacer"]
true-color = true
auto-completion = true
rulers = [80, 115]
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp] 
display-messages = true
display-signature-help-docs = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "╎"
